### ISSUE TITLE
Not working on URXVT

### ISSUE THREAD

**Issue by Durkh** [Kharacternyk/barva#2]
i'm using Arch + i3, i've already set the variables 

on Konsole when i start barva everything work just fine, but on URXVT, nothing happens

here some comparison, on left up there's konsole with barva, left down default konsole and on right it's URXVT with barva started but no difference from normal

![barva](https://user-images.githubusercontent.com/47802381/85112824-a6f9ac00-b1ec-11ea-8cc2-763ae8a26242.png)

**Comment by Kharacternyk** [comment]
Can't reproduce: I've installed `rxvt-unicode` and run `barva` just fine. It means that at least with the stock configuration `urxvt` supports `barva`. Can it be an issue in your config? What happens if you run `printf '\033]11;#FF0000\007'` in `urxvt`?
