### ISSUE TITLE
Unable to get it working in qterminal

### ISSUE THREAD

**Issue by tostiheld** [Kharacternyk/barva#3]
When I execute barva in qterminal, the background just stays in the original color. I executed ```export BARVA_SOURCE=$(/usr/share/barva/pa-get-default-monitor.sh)```. When I try for example rxvt-unicode, it does work.

**Comment by Kharacternyk** [comment]
It seems that `qterminal` doesn't support the necessary escape sequences, because neither `barva` nor `pywal` work there. There is nothing I can do, sorry.
