### ISSUE TITLE
Barva doesn't restore the original background color in rxvt-unicode

### ISSUE THREAD

**Issue by tostiheld** [Kharacternyk/barva#4]
When I execute barva in rxvt-unicode, it does pulse on the beat of my music. However, when I interrupt the program (ctrl-c), the background of the terminal emulator returns to black instead of my original background color.

**Comment by Kharacternyk** [comment]
Yes, that's expected. Unfortunately, there is no way for `barva` to know the background color that you use. As a workaround, specify your real background color in `BARVA_BG` instead of black.
