### ISSUE TITLE
i cant change the colour of the output

### ISSUE THREAD

**Issue by a8underscore** [Kharacternyk/barva#5]
video of issue: https://streamable.com/xl8ihm
What am i doing wrong? can i hardcode it so i dont need to set the vars ever?

thank you

**Comment by a8underscore** [comment]
command 
`BARVA_TARGET=#FF0000 barva` works

**Comment by Kharacternyk** [comment]
The issue in the video is that you are setting shell variables instead of environmental variables. Use `export BARVA_TARGET=something` instead of `BARVA_TARGET=something`.

**Comment by Kharacternyk** [comment]
You can put `export BARVA_TARGET=something` into your `.bashrc` or `.bash_profile` to make it persistent.

**Comment by a8underscore** [comment]
thank you
