### ISSUE TITLE
Add option to increase sensitivity

### ISSUE THREAD

**Issue by tom-kuca** [Kharacternyk/barva#7]
I tried barva on my ArchLinux with default configuration and it only set terminal background to black. 

I inspected the content of the `buffer` after `get_samples(s, sample_chunk_size, buffer);` in `src/main.c`, the values are all below 0.01 even if the music is reasonably loud, i.e.:

```
0.004364
0.005371
0.006134
0.006500
0.007019
0.007416
0.007568
0.007629
```
Maybe the reason is I'm using headphones. As a result, `queue_mean` is less than 0.01, `color_mean` always returns 0 or 1 and the background is set to black or almost black. 

If I multiply the value in `src/color.c` by 100, it works like a charm. Since it works for others as is, I propose to add an option to specify the sensitivity – the multiplier of the value.

**Comment by Kharacternyk** [comment]
Could it be that you run a sort of mixer that allows to change the volume on per-app basis? Such "volume changing" isn't the same as changing the system volume, because the former modifies the sample stream, while the latter does not. Therefore, if you have, say, 10% system volume and 100% music player volume, barva will run fine, but in case of 100% system volume and 10% player volume, barva will see not much more than silence.

P.S. Thank you for investigating it yourself instead of creating an issue with a title like "barva doesn't work".

**Comment by tom-kuca** [comment]
There is probably such a mixer. When I run pavucontrol, I can change the volume per-app. However, the volume in Output devices is set to 100 %.

![screenshot-2020-06-23-21:05:31](https://user-images.githubusercontent.com/171436/85450487-1bd83780-b599-11ea-9dfc-2186f1cdd49f.png)


I tried setting volume for barva to the max level:

![screenshot-2020-06-23-21:08:49](https://user-images.githubusercontent.com/171436/85450459-167aed00-b599-11ea-86cf-d73ad421ab82.png)


With both of them maxed out, I managed to get `#070707`. It has some effect, but not much. 

I noticed that the volume-bar in the pavucontrol which shows loudness in real time is also almost non-existent, I guess it matches the value 0.01.

<hr>

Update: Solved. 

If I change the volume in Input devices (11 % on screenshot), the volume-bar in pavucontrol will show higher value and the value will transfer to barva. Why the volume of an input device affects the value is beyond me, but it's a feature/bug of pulseaudio, not barva. I'm closing the issue, thanks for the hint.

![screenshot-2020-06-23-21:21:02](https://user-images.githubusercontent.com/171436/85450375-fcd9a580-b598-11ea-9e94-c98f564316af.png)

**Comment by Kharacternyk** [comment]
Did the issue go away after you increased or decreased the volume of "Monitor of Built-in Audio Analog Stereo"? If the answer is *decreased*, then I'll be very confused, but if the answer is increased, then the explanation is simple: barva reads the samples from the monitor and by increasing its volume you increase the values of the samples.

The reason why does the issue exist in the first place is still unclear. My only assumption is following: you have a rather high volume set for the output device (91% "Built-in Audio Analog Stereo") and it's likely that you have a rather low volume set in an audio player that you use and/or a rather low volume set for the player by PulseAudio (it could be seen in the Playback tab). If this is the case, then setting the volume in the player and/or for the player in pavucontrol to 100% and lowering the volume of "Built-in Audio Analog Stereo" instead should solve the issue.
